name: Release

on:
  release:
    types: [published]

permissions:
  contents: write  # Gives the action permission to attach files to your release

jobs:
  release:
    name: Prepare Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create ZIP archive
        run: |
          cd custom_components/connectivity_monitor && zip -r ../../connectivity_monitor.zip .

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: connectivity_monitor.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
